// <auto-generated />
namespace DBAToolV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class h6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(h6));
        
        string IMigrationMetadata.Id
        {
            get { return "201902161935291_h6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
