// <auto-generated />
namespace DBAToolV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m112));
        
        string IMigrationMetadata.Id
        {
            get { return "201902050321238_m112"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
